# Generated by Django 4.2.6 on 2023-12-26 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('hotel_app1', '0001_initial'), ('hotel_app1', '0002_hotel_hotel_id_alter_hotel_name_and_more'), ('hotel_app1', '0003_rename_hotel_id_hotel_hotelid'), ('hotel_app1', '0004_user_info'), ('hotel_app1', '0005_remove_user_info_address_remove_user_info_city_and_more'), ('hotel_app1', '0006_user_info_address_user_info_city_user_info_country_and_more'), ('hotel_app1', '0007_delete_user_info'), ('hotel_app1', '0008_user_info'), ('hotel_app1', '0009_alter_user_info_user'), ('hotel_app1', '0010_hotelbooking'), ('hotel_app1', '0011_alter_hotelbooking_address'), ('hotel_app1', '0012_alter_hotelbooking_zip_code'), ('hotel_app1', '0013_alter_hotelbooking_hotel'), ('hotel_app1', '0014_alter_hotelbooking_room_preference'), ('hotel_app1', '0015_alter_hotelbooking_room_preference'), ('hotel_app1', '0016_remove_hotelbooking_room_preference'), ('hotel_app1', '0017_hotelbooking_room_preference'), ('hotel_app1', '0018_alter_hotelbooking_room_preference'), ('hotel_app1', '0019_hotelbooking_no_of_days_and_more'), ('hotel_app1', '0020_hotel_price_per_night'), ('hotel_app1', '0021_rename_price_to_be_paid_hotelbooking_payment_price'), ('hotel_app1', '0022_creditcard_hotelbooking_card_no'), ('hotel_app1', '0023_alter_hotelbooking_card_no_delete_creditcard'), ('hotel_app1', '0024_creditcard_alter_hotelbooking_card_no'), ('hotel_app1', '0025_remove_hotelbooking_card_no'), ('hotel_app1', '0026_airline_flight_user_info_email_user_info_first_name_and_more'), ('hotel_app1', '0027_rename_arrival_flight_arrival_city_and_more'), ('hotel_app1', '0028_alter_flight_departure_date')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('hotelid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('price_per_night', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.hotel', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(default='', max_length=254)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('cvc', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_preference', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20, null=True)),
                ('no_of_days', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.AutoField(primary_key=True, serialize=False)),
                ('departure_city', models.CharField(max_length=250)),
                ('arrival_city', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.airline')),
                ('departure_date', models.DateField(default='2020-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_seats', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.flightbooking')),
            ],
        ),
    ]
