# Generated by Django 4.2.6 on 2023-12-28 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('busid', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField(default='2023-12-30')),
                ('departure_time', models.TimeField(default='12:00:00')),
                ('departure_city', models.CharField(max_length=250)),
                ('destination_city', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_seats', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusBookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.busbooking')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.buscompany'),
        ),
    ]
