# Generated by Django 4.2.6 on 2023-12-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.hotel', to_field='name'),
        ),
    ]
