# Generated by Django 4.2.6 on 2023-12-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0002_hotel_hotel_id_alter_hotel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_id',
            new_name='hotelid',
        ),
    ]
