# Generated by Django 4.2.6 on 2023-12-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0004_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user',
        ),
    ]
