# Generated by Django 4.2.6 on 2023-12-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0006_user_info_address_user_info_city_user_info_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
