# Generated by Django 4.2.6 on 2023-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0010_hotelbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
