# Generated by Django 4.2.6 on 2023-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0011_alter_hotelbooking_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
