# Generated by Django 4.2.6 on 2023-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0013_alter_hotelbooking_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_preference',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], max_length=20),
        ),
    ]
