# Generated by Django 4.2.6 on 2023-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0014_alter_hotelbooking_room_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_preference',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=20),
        ),
    ]
