# Generated by Django 4.2.6 on 2023-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0017_hotelbooking_room_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_preference',
            field=models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20, null=True),
        ),
    ]
