# Generated by Django 4.2.6 on 2023-12-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0019_hotelbooking_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.IntegerField(default=100),
        ),
    ]
