# Generated by Django 4.2.6 on 2023-12-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0020_hotel_price_per_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='price_to_be_paid',
            new_name='payment_price',
        ),
    ]
