# Generated by Django 4.2.6 on 2023-12-13 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app1', '0021_rename_price_to_be_paid_hotelbooking_payment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(default='', max_length=50)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('cvc', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='card_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.creditcard'),
        ),
    ]
