# Generated by Django 4.2.6 on 2023-12-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0022_creditcard_hotelbooking_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='card_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
