# Generated by Django 4.2.6 on 2023-12-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0024_creditcard_alter_hotelbooking_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='card_no',
        ),
    ]
