# Generated by Django 4.2.6 on 2023-12-26 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app1', '0025_remove_hotelbooking_card_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=250)),
                ('arrival', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.airline')),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user_info',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_info',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_info',
            name='zip_code',
            field=models.IntegerField(default=10000),
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_seats', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.flightbooking')),
            ],
        ),
    ]
