# Generated by Django 4.2.6 on 2023-12-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0027_rename_arrival_flight_arrival_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
