# Generated by Django 4.2.6 on 2023-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0029_alter_flight_departure_date_alter_hotel_hotelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default='2022-12-30'),
        ),
    ]
