# Generated by Django 4.2.6 on 2023-12-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0030_alter_flight_departure_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_city',
            new_name='destination_city',
        ),
    ]
