# Generated by Django 4.2.6 on 2023-12-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0031_rename_arrival_city_flight_destination_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('suiteid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('bedrooms', models.IntegerField(default=100)),
                ('size', models.IntegerField(default=100)),
                ('price_per_night', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotelServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.hotel', to_field='name')),
            ],
        ),
    ]
