# Generated by Django 4.2.6 on 2023-12-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0032_suites_hotelservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservices',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.hotel'),
        ),
    ]
