# Generated by Django 4.2.6 on 2023-12-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0033_alter_hotelservices_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelservices',
            old_name='hotel',
            new_name='hotel_id',
        ),
    ]
