# Generated by Django 4.2.6 on 2023-12-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0034_rename_hotel_hotelservices_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelservices',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
