# Generated by Django 4.2.6 on 2023-12-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0035_rename_hotel_id_hotelservices_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default='2023-12-30'),
        ),
    ]
