# Generated by Django 4.2.6 on 2023-12-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app1', '0036_flight_departure_time_alter_flight_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room_preference',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='suite_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel_app1.suites'),
        ),
    ]
