# Generated by Django 4.2.30 on 2026-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bus_buscompany_busbooking_busbookedseats_bus_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
