# Generated by Django 4.2.30 on 2026-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_user_info_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
