# Generated by Django 4.2.30 on 2026-10-03 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_model_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='busbookedseats',
            name='seat_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.bus'),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='num_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='payment_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='flightbookedseats',
            name='seat_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.flight'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='num_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='payment_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='no_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.suites'),
        ),
        migrations.AlterField(
            model_name='suites',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suites',
            name='price_per_night',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suites',
            name='size',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
